services:
  api:
    build:
      context: ../nextclimb-api
      # If your Dockerfile has a different name, uncomment the next line:
      # dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/1
    # This ensures Django waits for potential DB services if you add them later
    stdin_open: true
    tty: true

  ui:
    build:
      context: ../nextclimb-ui
    depends_on:
      - api
  redis:
    image: redis:7-alpine
    restart: always
    # Persistence is optional for a cache, but good for performance
    volumes:
      - redis_data:/data
volumes:
  redis_data:
