services:
  api:
    build:
      context: ../nextclimb-api
      # If your Dockerfile has a different name, uncomment the next line:
      # dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    # This ensures Django waits for potential DB services if you add them later
    stdin_open: true
    tty: true

  ui:
    build:
      context: ../nextclimb-ui
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
